export const RHEUM_DRUGS = [
  "Methotrexate",
  "Hydroxychloroquine",
  "Sulfasalazine",
  "Leflunomide",
  "Prednisolone",
  "Methylprednisolone",
  "Folic Acid",
  "Calcium + Vitamin D",
  "Tofacitinib",
  "Baricitinib",
  "Upadacitinib",
  "Adalimumab",
  "Etanercept",
  "Infliximab",
  "Rituximab",
  "Abatacept",
  "Tocilizumab",
  "Secukinumab",
  "Ixekizumab",
  "Belimumab",
  "Mycophenolate",
  "Azathioprine",
  "Cyclophosphamide",
  "Colchicine",
  "Allopurinol",
  "Febuxostat",
  "Naproxen",
  "Diclofenac",
  "Etoricoxib",
  "Celecoxib",
  "Omeprazole",
  "Pantoprazole",
];
