/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppPatientsIndexRouteImport } from './routes/_app.patients.index'
import { Route as AppPatientsNewRouteImport } from './routes/_app.patients.new'
import { Route as AppPatientsPatientIdIndexRouteImport } from './routes/_app.patients.$patientId.index'
import { Route as AppPatientsPatientIdEditRouteImport } from './routes/_app.patients.$patientId.edit'
import { Route as AppPatientsPatientIdVisitsNewRouteImport } from './routes/_app.patients.$patientId.visits.new'
import { Route as AppPatientsPatientIdVisitsVisitIdEditRouteImport } from './routes/_app.patients.$patientId.visits.$visitId.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsIndexRoute = AppPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsNewRoute = AppPatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsPatientIdIndexRoute =
  AppPatientsPatientIdIndexRouteImport.update({
    id: '/patients/$patientId/',
    path: '/patients/$patientId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppPatientsPatientIdEditRoute =
  AppPatientsPatientIdEditRouteImport.update({
    id: '/patients/$patientId/edit',
    path: '/patients/$patientId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppPatientsPatientIdVisitsNewRoute =
  AppPatientsPatientIdVisitsNewRouteImport.update({
    id: '/patients/$patientId/visits/new',
    path: '/patients/$patientId/visits/new',
    getParentRoute: () => AppRoute,
  } as any)
const AppPatientsPatientIdVisitsVisitIdEditRoute =
  AppPatientsPatientIdVisitsVisitIdEditRouteImport.update({
    id: '/patients/$patientId/visits/$visitId/edit',
    path: '/patients/$patientId/visits/$visitId/edit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/patients/new': typeof AppPatientsNewRoute
  '/patients/': typeof AppPatientsIndexRoute
  '/patients/$patientId/edit': typeof AppPatientsPatientIdEditRoute
  '/patients/$patientId/': typeof AppPatientsPatientIdIndexRoute
  '/patients/$patientId/visits/new': typeof AppPatientsPatientIdVisitsNewRoute
  '/patients/$patientId/visits/$visitId/edit': typeof AppPatientsPatientIdVisitsVisitIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/patients/new': typeof AppPatientsNewRoute
  '/patients': typeof AppPatientsIndexRoute
  '/patients/$patientId/edit': typeof AppPatientsPatientIdEditRoute
  '/patients/$patientId': typeof AppPatientsPatientIdIndexRoute
  '/patients/$patientId/visits/new': typeof AppPatientsPatientIdVisitsNewRoute
  '/patients/$patientId/visits/$visitId/edit': typeof AppPatientsPatientIdVisitsVisitIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/patients/new': typeof AppPatientsNewRoute
  '/_app/patients/': typeof AppPatientsIndexRoute
  '/_app/patients/$patientId/edit': typeof AppPatientsPatientIdEditRoute
  '/_app/patients/$patientId/': typeof AppPatientsPatientIdIndexRoute
  '/_app/patients/$patientId/visits/new': typeof AppPatientsPatientIdVisitsNewRoute
  '/_app/patients/$patientId/visits/$visitId/edit': typeof AppPatientsPatientIdVisitsVisitIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/patients/new'
    | '/patients/'
    | '/patients/$patientId/edit'
    | '/patients/$patientId/'
    | '/patients/$patientId/visits/new'
    | '/patients/$patientId/visits/$visitId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/patients/new'
    | '/patients'
    | '/patients/$patientId/edit'
    | '/patients/$patientId'
    | '/patients/$patientId/visits/new'
    | '/patients/$patientId/visits/$visitId/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/patients/new'
    | '/_app/patients/'
    | '/_app/patients/$patientId/edit'
    | '/_app/patients/$patientId/'
    | '/_app/patients/$patientId/visits/new'
    | '/_app/patients/$patientId/visits/$visitId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/': {
      id: '/_app/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AppPatientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/new': {
      id: '/_app/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof AppPatientsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/$patientId/': {
      id: '/_app/patients/$patientId/'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof AppPatientsPatientIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/$patientId/edit': {
      id: '/_app/patients/$patientId/edit'
      path: '/patients/$patientId/edit'
      fullPath: '/patients/$patientId/edit'
      preLoaderRoute: typeof AppPatientsPatientIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/$patientId/visits/new': {
      id: '/_app/patients/$patientId/visits/new'
      path: '/patients/$patientId/visits/new'
      fullPath: '/patients/$patientId/visits/new'
      preLoaderRoute: typeof AppPatientsPatientIdVisitsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/$patientId/visits/$visitId/edit': {
      id: '/_app/patients/$patientId/visits/$visitId/edit'
      path: '/patients/$patientId/visits/$visitId/edit'
      fullPath: '/patients/$patientId/visits/$visitId/edit'
      preLoaderRoute: typeof AppPatientsPatientIdVisitsVisitIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppPatientsNewRoute: typeof AppPatientsNewRoute
  AppPatientsIndexRoute: typeof AppPatientsIndexRoute
  AppPatientsPatientIdEditRoute: typeof AppPatientsPatientIdEditRoute
  AppPatientsPatientIdIndexRoute: typeof AppPatientsPatientIdIndexRoute
  AppPatientsPatientIdVisitsNewRoute: typeof AppPatientsPatientIdVisitsNewRoute
  AppPatientsPatientIdVisitsVisitIdEditRoute: typeof AppPatientsPatientIdVisitsVisitIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppPatientsNewRoute: AppPatientsNewRoute,
  AppPatientsIndexRoute: AppPatientsIndexRoute,
  AppPatientsPatientIdEditRoute: AppPatientsPatientIdEditRoute,
  AppPatientsPatientIdIndexRoute: AppPatientsPatientIdIndexRoute,
  AppPatientsPatientIdVisitsNewRoute: AppPatientsPatientIdVisitsNewRoute,
  AppPatientsPatientIdVisitsVisitIdEditRoute:
    AppPatientsPatientIdVisitsVisitIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
