/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSuccessRouteImport } from './routes/auth.success'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDas28RouteImport } from './routes/_app.das28'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppAiAssistantRouteImport } from './routes/_app.ai-assistant'
import { Route as AppPatientsIndexRouteImport } from './routes/_app.patients.index'
import { Route as AppPatientsNewRouteImport } from './routes/_app.patients.new'
import { Route as AppPatientsPatientIdIndexRouteImport } from './routes/_app.patients.$patientId.index'
import { Route as AppPatientsPatientIdJointMapRouteImport } from './routes/_app.patients.$patientId.joint-map'
import { Route as AppPatientsPatientIdEditRouteImport } from './routes/_app.patients.$patientId.edit'
import { Route as AppPatientsPatientIdDas28RouteImport } from './routes/_app.patients.$patientId.das28'
import { Route as AppPatientsPatientIdVisitsNewRouteImport } from './routes/_app.patients.$patientId.visits.new'
import { Route as AppPatientsPatientIdVisitsVisitIdEditRouteImport } from './routes/_app.patients.$patientId.visits.$visitId.edit'

const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/auth/success',
  path: '/auth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDas28Route = AppDas28RouteImport.update({
  id: '/das28',
  path: '/das28',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAssistantRoute = AppAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsIndexRoute = AppPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsNewRoute = AppPatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsPatientIdIndexRoute =
  AppPatientsPatientIdIndexRouteImport.update({
    id: '/patients/$patientId/',
    path: '/patients/$patientId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppPatientsPatientIdJointMapRoute =
  AppPatientsPatientIdJointMapRouteImport.update({
    id: '/patients/$patientId/joint-map',
    path: '/patients/$patientId/joint-map',
    getParentRoute: () => AppRoute,
  } as any)
const AppPatientsPatientIdEditRoute =
  AppPatientsPatientIdEditRouteImport.update({
    id: '/patients/$patientId/edit',
    path: '/patients/$patientId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppPatientsPatientIdDas28Route =
  AppPatientsPatientIdDas28RouteImport.update({
    id: '/patients/$patientId/das28',
    path: '/patients/$patientId/das28',
    getParentRoute: () => AppRoute,
  } as any)
const AppPatientsPatientIdVisitsNewRoute =
  AppPatientsPatientIdVisitsNewRouteImport.update({
    id: '/patients/$patientId/visits/new',
    path: '/patients/$patientId/visits/new',
    getParentRoute: () => AppRoute,
  } as any)
const AppPatientsPatientIdVisitsVisitIdEditRoute =
  AppPatientsPatientIdVisitsVisitIdEditRouteImport.update({
    id: '/patients/$patientId/visits/$visitId/edit',
    path: '/patients/$patientId/visits/$visitId/edit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/calendar': typeof AppCalendarRoute
  '/das28': typeof AppDas28Route
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/auth/success': typeof AuthSuccessRoute
  '/patients/new': typeof AppPatientsNewRoute
  '/patients/': typeof AppPatientsIndexRoute
  '/patients/$patientId/das28': typeof AppPatientsPatientIdDas28Route
  '/patients/$patientId/edit': typeof AppPatientsPatientIdEditRoute
  '/patients/$patientId/joint-map': typeof AppPatientsPatientIdJointMapRoute
  '/patients/$patientId/': typeof AppPatientsPatientIdIndexRoute
  '/patients/$patientId/visits/new': typeof AppPatientsPatientIdVisitsNewRoute
  '/patients/$patientId/visits/$visitId/edit': typeof AppPatientsPatientIdVisitsVisitIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/calendar': typeof AppCalendarRoute
  '/das28': typeof AppDas28Route
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/auth/success': typeof AuthSuccessRoute
  '/patients/new': typeof AppPatientsNewRoute
  '/patients': typeof AppPatientsIndexRoute
  '/patients/$patientId/das28': typeof AppPatientsPatientIdDas28Route
  '/patients/$patientId/edit': typeof AppPatientsPatientIdEditRoute
  '/patients/$patientId/joint-map': typeof AppPatientsPatientIdJointMapRoute
  '/patients/$patientId': typeof AppPatientsPatientIdIndexRoute
  '/patients/$patientId/visits/new': typeof AppPatientsPatientIdVisitsNewRoute
  '/patients/$patientId/visits/$visitId/edit': typeof AppPatientsPatientIdVisitsVisitIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/_app/ai-assistant': typeof AppAiAssistantRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/das28': typeof AppDas28Route
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/auth/success': typeof AuthSuccessRoute
  '/_app/patients/new': typeof AppPatientsNewRoute
  '/_app/patients/': typeof AppPatientsIndexRoute
  '/_app/patients/$patientId/das28': typeof AppPatientsPatientIdDas28Route
  '/_app/patients/$patientId/edit': typeof AppPatientsPatientIdEditRoute
  '/_app/patients/$patientId/joint-map': typeof AppPatientsPatientIdJointMapRoute
  '/_app/patients/$patientId/': typeof AppPatientsPatientIdIndexRoute
  '/_app/patients/$patientId/visits/new': typeof AppPatientsPatientIdVisitsNewRoute
  '/_app/patients/$patientId/visits/$visitId/edit': typeof AppPatientsPatientIdVisitsVisitIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile-setup'
    | '/ai-assistant'
    | '/calendar'
    | '/das28'
    | '/dashboard'
    | '/settings'
    | '/auth/success'
    | '/patients/new'
    | '/patients/'
    | '/patients/$patientId/das28'
    | '/patients/$patientId/edit'
    | '/patients/$patientId/joint-map'
    | '/patients/$patientId/'
    | '/patients/$patientId/visits/new'
    | '/patients/$patientId/visits/$visitId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile-setup'
    | '/ai-assistant'
    | '/calendar'
    | '/das28'
    | '/dashboard'
    | '/settings'
    | '/auth/success'
    | '/patients/new'
    | '/patients'
    | '/patients/$patientId/das28'
    | '/patients/$patientId/edit'
    | '/patients/$patientId/joint-map'
    | '/patients/$patientId'
    | '/patients/$patientId/visits/new'
    | '/patients/$patientId/visits/$visitId/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/profile-setup'
    | '/_app/ai-assistant'
    | '/_app/calendar'
    | '/_app/das28'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/auth/success'
    | '/_app/patients/new'
    | '/_app/patients/'
    | '/_app/patients/$patientId/das28'
    | '/_app/patients/$patientId/edit'
    | '/_app/patients/$patientId/joint-map'
    | '/_app/patients/$patientId/'
    | '/_app/patients/$patientId/visits/new'
    | '/_app/patients/$patientId/visits/$visitId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/success': {
      id: '/auth/success'
      path: '/auth/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/das28': {
      id: '/_app/das28'
      path: '/das28'
      fullPath: '/das28'
      preLoaderRoute: typeof AppDas28RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-assistant': {
      id: '/_app/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AppAiAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/': {
      id: '/_app/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AppPatientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/new': {
      id: '/_app/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof AppPatientsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/$patientId/': {
      id: '/_app/patients/$patientId/'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof AppPatientsPatientIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/$patientId/joint-map': {
      id: '/_app/patients/$patientId/joint-map'
      path: '/patients/$patientId/joint-map'
      fullPath: '/patients/$patientId/joint-map'
      preLoaderRoute: typeof AppPatientsPatientIdJointMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/$patientId/edit': {
      id: '/_app/patients/$patientId/edit'
      path: '/patients/$patientId/edit'
      fullPath: '/patients/$patientId/edit'
      preLoaderRoute: typeof AppPatientsPatientIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/$patientId/das28': {
      id: '/_app/patients/$patientId/das28'
      path: '/patients/$patientId/das28'
      fullPath: '/patients/$patientId/das28'
      preLoaderRoute: typeof AppPatientsPatientIdDas28RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/$patientId/visits/new': {
      id: '/_app/patients/$patientId/visits/new'
      path: '/patients/$patientId/visits/new'
      fullPath: '/patients/$patientId/visits/new'
      preLoaderRoute: typeof AppPatientsPatientIdVisitsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/$patientId/visits/$visitId/edit': {
      id: '/_app/patients/$patientId/visits/$visitId/edit'
      path: '/patients/$patientId/visits/$visitId/edit'
      fullPath: '/patients/$patientId/visits/$visitId/edit'
      preLoaderRoute: typeof AppPatientsPatientIdVisitsVisitIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiAssistantRoute: typeof AppAiAssistantRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppDas28Route: typeof AppDas28Route
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppPatientsNewRoute: typeof AppPatientsNewRoute
  AppPatientsIndexRoute: typeof AppPatientsIndexRoute
  AppPatientsPatientIdDas28Route: typeof AppPatientsPatientIdDas28Route
  AppPatientsPatientIdEditRoute: typeof AppPatientsPatientIdEditRoute
  AppPatientsPatientIdJointMapRoute: typeof AppPatientsPatientIdJointMapRoute
  AppPatientsPatientIdIndexRoute: typeof AppPatientsPatientIdIndexRoute
  AppPatientsPatientIdVisitsNewRoute: typeof AppPatientsPatientIdVisitsNewRoute
  AppPatientsPatientIdVisitsVisitIdEditRoute: typeof AppPatientsPatientIdVisitsVisitIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiAssistantRoute: AppAiAssistantRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppDas28Route: AppDas28Route,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppPatientsNewRoute: AppPatientsNewRoute,
  AppPatientsIndexRoute: AppPatientsIndexRoute,
  AppPatientsPatientIdDas28Route: AppPatientsPatientIdDas28Route,
  AppPatientsPatientIdEditRoute: AppPatientsPatientIdEditRoute,
  AppPatientsPatientIdJointMapRoute: AppPatientsPatientIdJointMapRoute,
  AppPatientsPatientIdIndexRoute: AppPatientsPatientIdIndexRoute,
  AppPatientsPatientIdVisitsNewRoute: AppPatientsPatientIdVisitsNewRoute,
  AppPatientsPatientIdVisitsVisitIdEditRoute:
    AppPatientsPatientIdVisitsVisitIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  AuthSuccessRoute: AuthSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
